# Welcome to Jekyll!
#remote_theme: "mmistakes/so-simple-theme"
# Website settings
locale: "en-US"

title: Yash Ganatra
description: Mech on Github!
keywords: yash,yashganatra, yashg1, blog,Thermal Engineer, Mechanical Engineer, Mechanical Engineer blog, Heat transfer, CFD, Product Development
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://yashg1.github.io/ # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /yashg1/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before



# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Yash Ganatra # Be used at blog posts' author.
  first_name: Yash  # Be used at index page about me section.
  last_name: Ganatra  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar_updated.jpg  # upload your avatar at directory and edit it.
  github_username: yashg1  # Leave blank if you don't have now
  linkedin_id: yashganatra # Leave blank if you don't have now
  email: gyash@protonmail.com   # Leave blank if you don't have now
  cv:   # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fa-fire
    - name: fa-car
  skill_icon2:
    - name: fa-cogs
    - name: fas fa-wrench
  desc: |
        Welcome to my website! I am a persevering and multifaceted mechanical engineer who enjoys turning designs into products through efficient collaboration.
        With experience in CAD, heat transfer, CFD, programing and hardware testing/troubleshooting, I can take on a variety of challenging roles. I like to keep learning and playing with the greatest and latest. Also, I helped build a car!
        I love soccer ⚽, 📖 and learning languages (current 🇨🇳).



# comment
#disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
 #name: yashganatra

# analytics
## google analytics
#ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  #id: UA-93473370-3

## google optimize
#go:
  # id:

## growingIO
#gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
words_per_minute: 200
timezone: America/New_York
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Plugins (previously gems:)
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
